name: Node sdk 2.x release

on:
  release:
    types: [released]
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn

      - name: update submodules
        run: |
          git submodule init
          git submodule update --remote

      - name: Build app
        run: |
          yarn build

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
