name: Milvus2 Node sdk check when open pr

on:
  pull_request:
    branches:
      - dev
    types: [opened, synchronize]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Read package.json
        uses: dutscher/read-package-json-endpoint-actions@v1.33.7
        id: package-json-endpoint

      - name: Run Milvus
        run: |
          wget https://raw.githubusercontent.com/milvus-io/milvus/master/deployments/docker/standalone/docker-compose.yml -O docker-compose.yml
          sed -i -e "s/milvusdb.*$/milvusdb\/milvus:${{ steps.package-json-endpoint.outputs.milvusVersion }}/g" docker-compose.yml
          docker-compose up -d

      - name: update submodules
        run: |
          git submodule init
          yarn pre

      - name: Run Test coverage
        run: |
          yarn
          yarn build-test
          yarn coverage
