name: Milvus2 Node sdk check when open pr

on:
  pull_request:
    branches:
      - dev
    types: [opened, synchronize]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Run Milvus
        run: |
          wget https://raw.githubusercontent.com/milvus-io/milvus/master/deployments/docker/standalone/docker-compose.yml -O docker-compose.yml
          sed -i -e 's/milvusdb.*$/milvusdb\/milvus:master-latest/g' docker-compose.yml
          docker-compose up -d

      - name: update submodules
        run: |
          git submodule init
          yarn pre

      - name: Run Test coverage
        run: |
          yarn
          yarn build-test
          yarn coverage
