name: Node sdk 2.x merge

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Run Milvus
        run: |
          wget https://raw.githubusercontent.com/milvus-io/milvus/master/deployments/docker/standalone/docker-compose.yml -O docker-compose.yml
          docker-compose up -d
      
      - name: update submodules
        run: |
          git submodule init
          git submodule update --remote

      - name: Run Test coverage
        run: |
          yarn
          yarn coverage

      - name: send to codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: bash <(curl -s https://codecov.io/bash)
